theme: jekyll-theme-midnight
title: "Team 2 Github Project"
description: "Team 2 Github Project"
gitorg: "https://github.com/PrishaB/Team2Reunion"
description: "We are working on implementing APIs from Spring project to this frontend project!"
google_analytics:
github: [metadata]